name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and publish
      run: |
        dotnet publish KlondikeSolitaire.Blazor/KlondikeSolitaire.Blazor.csproj \
          -c Release \
          -o publish \
          --no-restore \
          -p:GHPages=true

    - name: Change base href in index.html
      run: |
        sed -i 's|<base href="/" />|<base href="/KlondikeSolitaire---Vibecode/" />|g' publish/wwwroot/index.html

    - name: Update PWA manifest URLs
      run: |
        sed -i 's|"start_url": "/"|"start_url": "/KlondikeSolitaire---Vibecode/"|g' publish/wwwroot/manifest.json
        sed -i 's|"url": "/"|"url": "/KlondikeSolitaire---Vibecode/"|g' publish/wwwroot/manifest.json
        sed -i 's|"url": "/statistics"|"url": "/KlondikeSolitaire---Vibecode/statistics"|g' publish/wwwroot/manifest.json

    - name: Add .nojekyll file
      run: touch publish/wwwroot/.nojekyll

    - name: Copy index.html to 404.html (SPA fallback)
      run: cp publish/wwwroot/index.html publish/wwwroot/404.html

    - name: Verify files before upload
      run: |
        echo "Listing publish/wwwroot contents:"
        ls -la publish/wwwroot/
        echo "Checking for key files:"
        ls -la publish/wwwroot/_framework/blazor.webassembly.js
        ls -la publish/wwwroot/css/
        ls -la publish/wwwroot/index.html
        echo "Verifying base href was updated:"
        grep "base href" publish/wwwroot/index.html
        echo "Verifying manifest URLs were updated:"
        grep "start_url" publish/wwwroot/manifest.json
        grep "\"url\":" publish/wwwroot/manifest.json

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'publish/wwwroot'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

